### ISSUE TITLE
[SMS]  Thumbnail of contact not shown

### ISSUE THREAD

**Issue by duffydack** [grimpy/mconnect#1]
Great work fixing https://github.com/bboozzoo/mconnect/issues/58.
IDK, but would it be trivial to add thumbs for sms/messages?

**Comment by grimpy** [comment]
I don't think it's supported by kde-connect itself.
As far as I know sms/messages are apprearing is normal notifications which don't have any thumbnail information attached

**Comment by duffydack** [comment]
That would be cool.  Thanks

**Comment by grimpy** [comment]
@duffydack I found that there is some image data inside the notification which is now forwarded to your os notification. 

Depending on your SMS application the value of the image can differ some apps just set the appicon...

Any feedback is welcome

**Comment by duffydack** [comment]
That's improved the look a little for sure.  

![sway-2021-06-27_17-53-11](https://user-images.githubusercontent.com/41839511/123552972-b51fc800-d770-11eb-974a-d4f0208df7f2.png)


Using Google Messages.  The only messaging app really I wanted to receive notifications from (I filtered out everything else that I use and receive desktop notifs for on my OS).  I wonder where the contact icon is then.  Hmm

**Comment by grimpy** [comment]
Going to close this issue as there is nothing left to be done from this side. If you would like to persue this i suggest you file and issue in the kde-connect app @ https://invent.kde.org/network/kdeconnect-android
